apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wzi29djjc-go 
  janus-idp.io/tekton: wzi29djjc-go
  backstage.io/kubernetes-id: wzi29djjc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wzi29djjc-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  